name: test

on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"
      - run: make -C ./lexer test
